# Makefile for MO-P contest environment
# (c) 2008 Martin Mares <mj@ucw.cz>

DIRS+=mop/score
PROGS+=$(addprefix $(o)/mop/score/,mo-score-mop)

$(o)/mop/score/mo-score-mop: $(s)/mop/score/mo-score-mop.sh
