# Perl modules

DIRS+=sherlock/perl
EXTRA_RUNDIRS+=lib/perl5/Sherlock
SHERLOCK_PERL_MODS=$(addprefix $(o)/sherlock/perl/,Object.pm)
PROGS+=$(SHERLOCK_PERL_MODS)

$(SHERLOCK_PERL_MODS): PERL_MODULE_DIR=Sherlock
