<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['per_page'] = 20;
$config['use_page_numbers'] = TRUE;
$config['num_links'] = 5;
$config['full_tag_open'] = '<ul>';
$config['full_tag_close'] = '</ul>';
$config['cur_tag_open'] = '<li class="active"><a href="#">';
$config['cur_tag_close'] = '</a></li>';
$config['first_link'] = '&lt;&lt;';
$config['first_tag_open'] = '<li>';
$config['first_tag_close'] = '</li>';
$config['last_link'] = '&gt;&gt;';
$config['last_tag_open'] = '<li>';
$config['last_tag_close'] = '</li>';
$config['next_tag_open'] = '<li>';
$config['next_tag_close'] = '</li>';
$config['prev_tag_open'] = '<li>';
$config['prev_tag_close'] = '</li>';
$config['num_tag_open'] = '<li>';
$config['num_tag_close'] = '</li>';