# Makefile for MO-P contest environment
# (c) 2010 Martin Mares <mj@ucw.cz>

DIRS+=mop/calibrate
PROGS+=$(addprefix $(o)/mop/calibrate/,cal-prepare cal-try)

$(o)/mop/calibrate/cal-prepare: $(s)/mop/calibrate/cal-prepare.sh
$(o)/mop/calibrate/cal-try: $(s)/mop/calibrate/cal-try.sh
